### ISSUE TITLE
Friends List design

### ISSUE THREAD

**Issue by jaivignesh23** [ayushdj/Stick-It-To-em#2]
Design layout for the list

**Comment by jaivignesh23** [comment]
### TO-DO

- [x]  New Activity creation
- [x]  Recycler view for the list view
- [x]  Card view for display
- [x]  On-Click listener to open the conversation activity
