### ISSUE TITLE
Conversation View Design

### ISSUE THREAD

**Issue by jaivignesh23** [ayushdj/Stick-It-To-em#3]

**Comment by jaivignesh23** [comment]
### TO-DO
- [ ] New Activity creation
- [ ] Recycler view for the list view
- [ ] Card view
- [ ] On-Click listener to open the conversation activity
